### PR TITLE
drop the elf2bin.sh script; recommend the replacement in particle-tools

### PR DESCRIPTION
**Pull request by japaric**
the Rust version of `elf2bin` works on Windows \o/

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cf04684 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cf04684 with merge cf04684...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/232949603?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing cf046841321f77c49ed346523a85e2668dffca9f to master...

**Pull request merged**
