### PR TITLE
pass -Wl,--whole-archive to the linker *after* the Rust objects has been passed

### LINKED ISSUE #1: Doesn't link when compiled without `--release`
I think that to fix this the order of the linker arguments need to be tweaked a little to place the Rust objects outside the whole-archive group.

### PR DESCRIPTION
**Pull request by japaric**
fixes #1

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 25b1166 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 25b1166 with merge 25b1166...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/232985638?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4104cb2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4104cb2 with merge 4104cb2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/233001137?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 4104cb25d3fccfac130fbad509678ca5a965bd1f to master...

**Pull request merged**
