### PR TITLE
add example for the Cloud variable API

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e1f28ff has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e1f28ff with merge e1f28ff...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/231998082?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e1f28ffecfa408d54a1cb298fc54bf0baf27fdd3 to master...

**Pull request merged**
