### PR TITLE
drop the custom target and use -Z pre-link-arg

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 4104cb2) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2fbfafb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2fbfafb with merge 2fbfafb...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/246015692?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/246015692?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2fbfafb0226e8603c8bf017eb111e2b76af05afb to master...

**Pull request merged**
