### PR TITLE
beef up the documentation

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8abc353 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8abc353 with merge 8abc353...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/233428011?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 8abc3535d8e3a47c120a49f459c449bf3fe77fbf to master...

**Pull request merged**
