### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ae0b5c7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ae0b5c7 with merge ae0b5c7...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 99d3a83 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 99d3a83 with merge 99d3a83...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4ddd560 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4ddd560 with merge 4ddd560...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a1e1031 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a1e1031 with merge a1e1031...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/231598481?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a1e10312874fd59326e1a72b95aa77af4a4060aa to master...

**Pull request merged**
