### PR TITLE
use the higher level API

### PR DESCRIPTION
**Pull request by japaric**
updated some examples to use the safe API implemented in
japaric/particle-hal#10. I also have an idea to make global variable safe but
haven't implemented it. The basic idea is that since there doesn't seem to be a
mechanism for preemption then accessing global variables is safe as long as you
don't hand out more than one mutable reference (`&mut-`) to the variable at a
time and the simplest way to preserve that rule is that is to only hand out
shared (`&-`) references to global data. (Mutation through shared references can
be achieved using Cell / RefCell).

cc @dbrgn

### CODE REVIEW

**Comment by dbrgn** [comment]
Looks good so far! :)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1eb58e5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1eb58e5 with merge 1eb58e5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/233024171?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 1eb58e50cc9a0021f6bb088de0bcbe8948d36cc7 to master...

**Pull request merged**
