### PR TITLE
adapt to upstream changes, add cloud API example

### PR DESCRIPTION
**Pull request by japaric**
cc @dbrgn

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 71da24d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 71da24d with merge 71da24d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/photon-quickstart/builds/231989670?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 71da24d5bf02bb8cd56937af6be741a94c57c704 to master...

**Pull request merged**
